import type { IndustryConfig } from '@rule-tool/industry-core';

export const hvacConfig: IndustryConfig = {
  id: 'hvac',
  name: 'HVAC Pro Suite',
  tagline: 'Professional Heating, Ventilation & Air Conditioning',

  branding: {
    primaryColor: '#0369a1',     // Sky blue (cooling)
    secondaryColor: '#dc2626',   // Red (heating)
    accentColor: '#16a34a',      // Green (efficiency)
    logo: '/logos/hvacpro.svg',
    favicon: '/favicon.ico',
    heroImage: '/images/hvac-hero.jpg',
  },

  terminology: {
    job: 'Project',
    jobPlural: 'Projects',
    client: 'Customer',
    clientPlural: 'Customers',
    estimate: 'Proposal',
    estimatePlural: 'Proposals',
    crew: 'Install Team',
    phase: 'Phase',
    phasePlural: 'Phases',
  },

  features: {
    jobs: true,
    estimates: true,
    sov: true,
    crm: true,
    expenses: true,
    invoicing: true,
    scheduling: true,
    crew: true,
    mileage: true,
    receipts: true,
    reports: true,
    areaMeasurement: true,  // For roof RTU placement, line sets
    stallTool: false,
    concreteTool: false,
    roofingTool: true,  // Useful for rooftop unit placement
  },

  phases: [
    {
      name: 'Assessment & Design',
      tasks: ['Site survey', 'Load calculation', 'Equipment selection', 'Duct design', 'Create proposal'],
      color: '#3b82f6',
    },
    {
      name: 'Permits & Procurement',
      tasks: ['Pull permits', 'Order equipment', 'Order materials', 'Schedule delivery', 'Coordinate crane if needed'],
      color: '#f59e0b',
    },
    {
      name: 'Demolition & Prep',
      tasks: ['Remove old equipment', 'Modify ductwork', 'Electrical prep', 'Set equipment pads/curbs', 'Run new circuits'],
      color: '#ef4444',
    },
    {
      name: 'Equipment Installation',
      tasks: ['Set outdoor unit', 'Set indoor unit/air handler', 'Install RTU/package unit', 'Mount minisplit heads', 'Connect refrigerant lines'],
      color: '#8b5cf6',
    },
    {
      name: 'Ductwork & Piping',
      tasks: ['Install supply ducts', 'Install return ducts', 'Install registers/grilles', 'Condensate piping', 'Gas piping if applicable'],
      color: '#06b6d4',
    },
    {
      name: 'Controls & Wiring',
      tasks: ['Install thermostat', 'Run control wiring', 'Program controls', 'Connect to BMS if applicable', 'Test safety circuits'],
      color: '#84cc16',
    },
    {
      name: 'Startup & Commissioning',
      tasks: ['Charge refrigerant', 'Test airflow', 'Balance system', 'Verify temperatures', 'Commission controls'],
      color: '#22c55e',
    },
    {
      name: 'Closeout',
      tasks: ['Customer training', 'Warranty registration', 'Final inspection', 'Documentation handoff', 'Permit closeout'],
      color: '#6366f1',
    },
  ],

  services: [
    // Residential Systems
    {
      id: 'res-split-system',
      name: 'Residential Split System',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 2800,
      minimumCharge: 5000,
      description: 'Standard efficiency split system install (14-16 SEER)',
    },
    {
      id: 'res-split-premium',
      name: 'High-Efficiency Split System',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 3500,
      minimumCharge: 7000,
      description: 'High efficiency split system (17+ SEER)',
    },
    {
      id: 'res-heat-pump',
      name: 'Heat Pump System',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 3200,
      minimumCharge: 6000,
      description: 'Heat pump with backup heat strips',
    },
    {
      id: 'minisplit-single',
      name: 'Ductless Minisplit (Single Zone)',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 3500,
      minimumCharge: 3500,
      description: 'Single head minisplit system',
    },
    {
      id: 'minisplit-multi',
      name: 'Ductless Minisplit (Multi-Zone)',
      measurementType: 'count',
      unit: 'head',
      defaultRate: 2000,
      minimumCharge: 6000,
      description: 'Per indoor head, multi-zone system',
    },
    // Commercial Systems
    {
      id: 'comm-rtu',
      name: 'Rooftop Unit (RTU)',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 1800,
      minimumCharge: 8000,
      description: 'Package rooftop unit install',
    },
    {
      id: 'comm-rtu-vav',
      name: 'RTU with VAV',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 2200,
      minimumCharge: 12000,
      description: 'RTU with variable air volume system',
    },
    {
      id: 'comm-vrf',
      name: 'VRF/VRV System',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 4500,
      minimumCharge: 25000,
      description: 'Variable refrigerant flow system',
    },
    {
      id: 'comm-chiller',
      name: 'Chiller System',
      measurementType: 'count',
      unit: 'ton',
      defaultRate: 1200,
      minimumCharge: 50000,
      description: 'Chilled water system (chiller only)',
    },
    {
      id: 'comm-boiler',
      name: 'Boiler System',
      measurementType: 'count',
      unit: 'mbh',
      defaultRate: 45,
      minimumCharge: 8000,
      description: 'Hot water/steam boiler install',
    },
    // Ductwork
    {
      id: 'duct-supply',
      name: 'Supply Ductwork',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 18,
      minimumCharge: 500,
      description: 'Insulated supply duct, materials and labor',
    },
    {
      id: 'duct-return',
      name: 'Return Ductwork',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 15,
      minimumCharge: 400,
      description: 'Return air duct run',
    },
    {
      id: 'duct-flex',
      name: 'Flex Duct Runs',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 8,
      minimumCharge: 200,
      description: 'Flexible insulated duct',
    },
    {
      id: 'register-supply',
      name: 'Supply Register/Diffuser',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 85,
      minimumCharge: 85,
      description: 'Supply air outlet with boot',
    },
    {
      id: 'register-return',
      name: 'Return Grille',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 75,
      minimumCharge: 75,
      description: 'Return air grille with filter if applicable',
    },
    // Add-ons and Accessories
    {
      id: 'thermostat-basic',
      name: 'Programmable Thermostat',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 250,
      minimumCharge: 250,
      description: 'Standard programmable thermostat',
    },
    {
      id: 'thermostat-smart',
      name: 'Smart Thermostat',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 450,
      minimumCharge: 450,
      description: 'WiFi-enabled smart thermostat',
    },
    {
      id: 'zoning-damper',
      name: 'Zone Damper',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 350,
      minimumCharge: 350,
      description: 'Motorized zone damper with actuator',
    },
    {
      id: 'air-purifier',
      name: 'Whole-Home Air Purifier',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 1200,
      minimumCharge: 1200,
      description: 'In-duct air purification system',
    },
    {
      id: 'humidifier',
      name: 'Whole-Home Humidifier',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 650,
      minimumCharge: 650,
      description: 'Bypass or steam humidifier',
    },
    {
      id: 'uv-light',
      name: 'UV Light System',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 550,
      minimumCharge: 550,
      description: 'Coil-mounted UV germicidal light',
    },
    // Service Items
    {
      id: 'lineset',
      name: 'Refrigerant Line Set',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 25,
      minimumCharge: 150,
      description: 'Insulated copper line set',
    },
    {
      id: 'electrical-circuit',
      name: 'New Electrical Circuit',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 450,
      minimumCharge: 450,
      description: '220V or 110V dedicated circuit',
    },
    {
      id: 'gas-piping',
      name: 'Gas Piping',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 35,
      minimumCharge: 250,
      description: 'Black iron or CSST gas line',
    },
    {
      id: 'condensate-drain',
      name: 'Condensate Drain Line',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 12,
      minimumCharge: 150,
      description: 'PVC condensate drainage',
    },
    {
      id: 'crane-service',
      name: 'Crane Service',
      measurementType: 'time',
      unit: 'hour',
      defaultRate: 350,
      minimumCharge: 700,
      description: 'Crane rental for rooftop equipment',
    },
    {
      id: 'equipment-removal',
      name: 'Old Equipment Removal',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 400,
      minimumCharge: 400,
      description: 'Remove and dispose of old unit',
    },
    {
      id: 'refrigerant-recovery',
      name: 'Refrigerant Recovery',
      measurementType: 'count',
      unit: 'lb',
      defaultRate: 15,
      minimumCharge: 150,
      description: 'EPA-compliant refrigerant recovery',
    },
  ],

  customFields: [
    {
      key: 'building_type',
      label: 'Building Type',
      type: 'select',
      options: ['Single Family', 'Multi-Family', 'Office', 'Retail', 'Restaurant', 'Warehouse', 'School', 'Healthcare', 'Industrial'],
      required: true,
    },
    {
      key: 'conditioned_sqft',
      label: 'Conditioned Square Footage',
      type: 'number',
      required: true,
      helpText: 'Total heated/cooled floor area',
    },
    {
      key: 'num_stories',
      label: 'Number of Stories',
      type: 'number',
      required: true,
    },
    {
      key: 'climate_zone',
      label: 'Climate Zone',
      type: 'select',
      options: ['Zone 1 (Hot-Humid)', 'Zone 2 (Hot-Dry)', 'Zone 3 (Mixed-Humid)', 'Zone 4 (Mixed-Dry)', 'Zone 5 (Cold)', 'Zone 6 (Very Cold)', 'Zone 7 (Subarctic)'],
      helpText: 'IECC climate zone',
    },
    {
      key: 'system_type',
      label: 'System Type',
      type: 'select',
      options: ['Split System', 'Heat Pump', 'Package Unit/RTU', 'Minisplit', 'VRF/VRV', 'Chilled Water', 'Boiler + AHU'],
      required: true,
    },
    {
      key: 'efficiency_tier',
      label: 'Efficiency Tier',
      type: 'select',
      options: ['Standard (14 SEER)', 'High Efficiency (16-17 SEER)', 'Premium (18+ SEER/Inverter)'],
    },
    {
      key: 'scope_type',
      label: 'Scope of Work',
      type: 'select',
      options: ['New Construction', 'Change Out (Like-for-Like)', 'Retrofit/Upgrade', 'Add-On System'],
      required: true,
    },
    {
      key: 'duct_modification',
      label: 'Ductwork Scope',
      type: 'select',
      options: ['Reuse Existing', 'Minor Modifications', 'Major Modifications', 'Complete Replacement', 'New Duct System'],
    },
    {
      key: 'equipment_location',
      label: 'Equipment Location',
      type: 'select',
      options: ['Ground Level', 'Rooftop', 'Attic', 'Basement/Crawl', 'Mechanical Room', 'Closet'],
    },
    {
      key: 'access_difficulty',
      label: 'Access Difficulty',
      type: 'select',
      options: ['Easy', 'Moderate', 'Difficult', 'Crane Required'],
      helpText: 'Affects labor multipliers',
    },
    {
      key: 'calculated_tonnage',
      label: 'Calculated Tonnage',
      type: 'number',
      helpText: 'From Manual J or load calc (tons)',
    },
    {
      key: 'calculated_heating_btuh',
      label: 'Heating Load (BTU/h)',
      type: 'number',
      helpText: 'From Manual J or load calc',
    },
    {
      key: 'permit_required',
      label: 'Permit Required',
      type: 'boolean',
    },
    {
      key: 'structural_work',
      label: 'Structural Work Needed',
      type: 'boolean',
      helpText: 'Roof curbs, equipment pads, etc.',
    },
  ],

  reports: [
    {
      id: 'revenue',
      name: 'Revenue Report',
      description: 'Total revenue by period',
      icon: 'DollarSign',
    },
    {
      id: 'profitability',
      name: 'Project Profitability',
      description: 'Profit margin per project',
      icon: 'TrendingUp',
    },
    {
      id: 'equipment-mix',
      name: 'Equipment Mix',
      description: 'Systems installed by type/brand',
      icon: 'PieChart',
    },
    {
      id: 'efficiency-trends',
      name: 'Efficiency Trends',
      description: 'SEER ratings sold over time',
      icon: 'Zap',
    },
    {
      id: 'crew-productivity',
      name: 'Crew Productivity',
      description: 'Installs per day, labor efficiency',
      icon: 'Users',
    },
    {
      id: 'warranty-claims',
      name: 'Warranty Claims',
      description: 'Callbacks and warranty work',
      icon: 'Shield',
    },
    {
      id: 'load-calc-accuracy',
      name: 'Load Calc Accuracy',
      description: 'Compare estimates to actuals',
      icon: 'Target',
    },
  ],

  navigation: [
    { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Projects', href: '/jobs', icon: 'Briefcase' },
    { label: 'Proposals', href: '/estimates', icon: 'FileText' },
    { label: 'Customers', href: '/contacts', icon: 'Users' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Crew', href: '/crew', icon: 'HardHat' },
    { label: 'Invoices', href: '/invoices', icon: 'Receipt' },
    { label: 'Expenses', href: '/expenses', icon: 'CreditCard' },
    { label: 'Load Calc', href: '/hvac/load-calc', icon: 'Calculator' },
    { label: 'Reports', href: '/reports', icon: 'BarChart3' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
};

export default hvacConfig;
