import { IndustryConfig } from './types';

export const fencingConfig: IndustryConfig = {
  id: 'fencing',
  name: 'FencePro Suite',
  tagline: 'Professional Fencing & Gates',

  branding: {
    primaryColor: '#78350f',     // Warm brown (wood)
    secondaryColor: '#1c1917',   // Dark iron
    accentColor: '#16a34a',      // Green (landscaping tie-in)
    logo: '/logos/fencepro.svg',
    favicon: '/favicon.ico',
    heroImage: '/images/fencing-hero.jpg',
  },

  terminology: {
    job: 'Project',
    jobPlural: 'Projects',
    client: 'Property Owner',
    clientPlural: 'Property Owners',
    estimate: 'Quote',
    estimatePlural: 'Quotes',
    crew: 'Install Crew',
    phase: 'Stage',
    phasePlural: 'Stages',
  },

  features: {
    jobs: true,
    estimates: true,
    sov: true,
    crm: true,
    expenses: true,
    invoicing: true,
    scheduling: true,
    crew: true,
    mileage: true,
    receipts: true,
    reports: true,
    areaMeasurement: true,
    // Specialized tools
    stallTool: false,
    concreteTool: true,  // For post holes
    roofingTool: false,
  },

  phases: [
    {
      name: 'Survey & Layout',
      tasks: ['Property survey', 'Locate utilities', 'Mark fence line', 'Measure perimeter', 'Identify grade changes'],
      color: '#3b82f6',
    },
    {
      name: 'Site Prep',
      tasks: ['Clear vegetation', 'Remove old fence', 'Grade if needed', 'Set string line'],
      color: '#f59e0b',
    },
    {
      name: 'Post Installation',
      tasks: ['Dig post holes', 'Set corner posts', 'Set line posts', 'Pour concrete', 'Allow cure time'],
      color: '#ef4444',
    },
    {
      name: 'Fence Installation',
      tasks: ['Install rails', 'Attach pickets/panels', 'Install gates', 'Add hardware', 'Check level/plumb'],
      color: '#22c55e',
    },
    {
      name: 'Finish & Cleanup',
      tasks: ['Stain/seal if wood', 'Touch up paint', 'Clean site', 'Customer walkthrough', 'Warranty paperwork'],
      color: '#8b5cf6',
    },
  ],

  services: [
    {
      id: 'wood-privacy-6ft',
      name: '6ft Wood Privacy Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 35,
      minimumCharge: 1500,
      description: 'Cedar or pressure-treated, dog-ear or flat top',
    },
    {
      id: 'wood-privacy-8ft',
      name: '8ft Wood Privacy Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 45,
      minimumCharge: 2000,
      description: 'Extra tall privacy fence',
    },
    {
      id: 'chain-link-4ft',
      name: '4ft Chain Link Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 18,
      minimumCharge: 800,
      description: 'Galvanized chain link with posts',
    },
    {
      id: 'chain-link-6ft',
      name: '6ft Chain Link Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 22,
      minimumCharge: 1000,
      description: 'Galvanized chain link with posts',
    },
    {
      id: 'vinyl-privacy',
      name: 'Vinyl Privacy Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 40,
      minimumCharge: 2000,
      description: 'Low-maintenance vinyl privacy',
    },
    {
      id: 'aluminum-ornamental',
      name: 'Aluminum Ornamental',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 55,
      minimumCharge: 2500,
      description: 'Decorative aluminum fencing',
    },
    {
      id: 'wrought-iron',
      name: 'Wrought Iron',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 85,
      minimumCharge: 3000,
      description: 'Custom wrought iron fencing',
    },
    {
      id: 'split-rail',
      name: 'Split Rail Fence',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 15,
      minimumCharge: 500,
      description: 'Rustic 2 or 3 rail fence',
    },
    {
      id: 'single-gate',
      name: 'Single Walk Gate',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 350,
      minimumCharge: 350,
      description: '3-4ft walk-through gate with hardware',
    },
    {
      id: 'double-gate',
      name: 'Double Drive Gate',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 750,
      minimumCharge: 750,
      description: '10-12ft drive-through gate',
    },
    {
      id: 'sliding-gate',
      name: 'Sliding Gate',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 2500,
      minimumCharge: 2500,
      description: 'Automated sliding gate system',
    },
    {
      id: 'post-replacement',
      name: 'Post Replacement',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 150,
      minimumCharge: 300,
      description: 'Replace broken/rotted post',
    },
    {
      id: 'fence-removal',
      name: 'Old Fence Removal',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 5,
      minimumCharge: 250,
      description: 'Remove and haul away existing fence',
    },
    {
      id: 'staining',
      name: 'Fence Staining/Sealing',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 8,
      minimumCharge: 400,
      description: 'Both sides, per linear foot',
    },
  ],

  customFields: [
    {
      key: 'fence_type',
      label: 'Fence Type',
      type: 'select',
      options: ['Wood Privacy', 'Chain Link', 'Vinyl', 'Aluminum', 'Wrought Iron', 'Split Rail', 'Farm/Ranch'],
      required: true,
    },
    {
      key: 'fence_height',
      label: 'Fence Height',
      type: 'select',
      options: ['3ft', '4ft', '5ft', '6ft', '8ft', 'Custom'],
      required: true,
    },
    {
      key: 'total_linear_feet',
      label: 'Total Linear Feet',
      type: 'number',
      required: true,
      helpText: 'Perimeter measurement',
    },
    {
      key: 'corner_posts',
      label: 'Corner Posts',
      type: 'number',
      helpText: 'Number of corner/end posts needed',
    },
    {
      key: 'gate_count',
      label: 'Number of Gates',
      type: 'number',
    },
    {
      key: 'terrain',
      label: 'Terrain',
      type: 'select',
      options: ['Flat', 'Slight Slope', 'Moderate Slope', 'Steep Slope', 'Rocky'],
    },
    {
      key: 'permit_required',
      label: 'Permit Required',
      type: 'boolean',
      helpText: 'Check local codes for fence permits',
    },
    {
      key: 'hoa_approval',
      label: 'HOA Approval Needed',
      type: 'boolean',
    },
  ],

  reports: [
    {
      id: 'revenue',
      name: 'Revenue Report',
      description: 'Total revenue by period',
      icon: 'DollarSign',
    },
    {
      id: 'profitability',
      name: 'Project Profitability',
      description: 'Profit margin per project',
      icon: 'TrendingUp',
    },
    {
      id: 'crew-productivity',
      name: 'Crew Productivity',
      description: 'Linear feet installed per day',
      icon: 'Users',
    },
    {
      id: 'material-usage',
      name: 'Material Usage',
      description: 'Posts, pickets, concrete tracking',
      icon: 'Package',
    },
    {
      id: 'warranty-tracker',
      name: 'Warranty Tracker',
      description: 'Active warranties by project',
      icon: 'Shield',
    },
  ],

  navigation: [
    { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Projects', href: '/jobs', icon: 'Briefcase' },
    { label: 'Quotes', href: '/estimates', icon: 'FileText' },
    { label: 'Customers', href: '/contacts', icon: 'Users' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Crew', href: '/crew', icon: 'HardHat' },
    { label: 'Invoices', href: '/invoices', icon: 'Receipt' },
    { label: 'Expenses', href: '/expenses', icon: 'CreditCard' },
    { label: 'Reports', href: '/reports', icon: 'BarChart3' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
};

export default fencingConfig;
