import type { IndustryConfig } from '@rule-tool/industry-core';

export const paintingConfig: IndustryConfig = {
  id: 'painting',
  name: 'PaintPro Suite',
  tagline: 'Professional Painting & Coatings',

  branding: {
    primaryColor: '#4338ca',     // Indigo (paint can)
    secondaryColor: '#1e1b4b',   // Dark indigo
    accentColor: '#f59e0b',      // Gold accent
    logo: '/logos/paintpro.svg',
    favicon: '/favicon.ico',
    heroImage: '/images/painting-hero.jpg',
  },

  terminology: {
    job: 'Project',
    jobPlural: 'Projects',
    client: 'Client',
    clientPlural: 'Clients',
    estimate: 'Bid',
    estimatePlural: 'Bids',
    crew: 'Painters',
    phase: 'Stage',
    phasePlural: 'Stages',
  },

  features: {
    jobs: true,
    estimates: true,
    sov: true,
    crm: true,
    expenses: true,
    invoicing: true,
    scheduling: true,
    crew: true,
    mileage: true,
    receipts: true,
    reports: true,
    areaMeasurement: true,
    // Specialized tools
    stallTool: false,
    concreteTool: false,
    roofingTool: false,
  },

  phases: [
    {
      name: 'Estimate & Color',
      tasks: ['Measure surfaces', 'Assess condition', 'Color consultation', 'Provide samples', 'Create proposal'],
      color: '#3b82f6',
    },
    {
      name: 'Prep Work',
      tasks: ['Protect floors/furniture', 'Pressure wash exterior', 'Scrape loose paint', 'Sand surfaces', 'Caulk gaps', 'Prime stains'],
      color: '#f59e0b',
    },
    {
      name: 'Repairs',
      tasks: ['Patch holes', 'Fix drywall damage', 'Replace rotted wood', 'Repair trim', 'Texture matching'],
      color: '#ef4444',
    },
    {
      name: 'Painting',
      tasks: ['Cut in edges', 'Roll walls/ceilings', 'Paint trim', 'Apply second coat', 'Touch-ups'],
      color: '#22c55e',
    },
    {
      name: 'Cleanup & Inspect',
      tasks: ['Remove tape/plastic', 'Clean windows/fixtures', 'Final touch-ups', 'Customer walkthrough', 'Provide care instructions'],
      color: '#8b5cf6',
    },
  ],

  services: [
    // Interior Services
    {
      id: 'interior-walls',
      name: 'Interior Walls',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 3.5,
      minimumCharge: 500,
      description: '2 coats on walls (per sqft wall area)',
    },
    {
      id: 'interior-ceiling',
      name: 'Interior Ceiling',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 2.5,
      minimumCharge: 400,
      description: 'Flat ceiling painting',
    },
    {
      id: 'interior-trim',
      name: 'Interior Trim/Doors',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 4,
      minimumCharge: 300,
      description: 'Baseboards, crown, door frames',
    },
    {
      id: 'interior-door',
      name: 'Interior Door (both sides)',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 85,
      minimumCharge: 85,
      description: 'Prep, prime, 2 coats',
    },
    {
      id: 'cabinet-painting',
      name: 'Cabinet Painting',
      measurementType: 'count',
      unit: 'door',
      defaultRate: 75,
      minimumCharge: 1500,
      description: 'Per cabinet door/drawer front',
    },
    // Exterior Services
    {
      id: 'exterior-siding',
      name: 'Exterior Siding',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 4,
      minimumCharge: 2000,
      description: 'Prep, prime, 2 coats',
    },
    {
      id: 'exterior-trim',
      name: 'Exterior Trim',
      measurementType: 'length',
      unit: 'ft',
      defaultRate: 5,
      minimumCharge: 500,
      description: 'Fascia, soffits, window trim',
    },
    {
      id: 'exterior-door',
      name: 'Exterior Door',
      measurementType: 'count',
      unit: 'each',
      defaultRate: 150,
      minimumCharge: 150,
      description: 'Entry door, both sides',
    },
    {
      id: 'deck-staining',
      name: 'Deck Staining',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 3,
      minimumCharge: 500,
      description: 'Clean, sand, apply stain',
    },
    {
      id: 'fence-painting',
      name: 'Fence Painting/Staining',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 2.5,
      minimumCharge: 400,
      description: 'Both sides per sqft',
    },
    {
      id: 'garage-floor',
      name: 'Garage Floor Epoxy',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 6,
      minimumCharge: 1200,
      description: 'Prep, prime, 2-part epoxy',
    },
    // Prep/Repair Services
    {
      id: 'pressure-wash',
      name: 'Pressure Washing',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 0.35,
      minimumCharge: 200,
      description: 'Surface prep cleaning',
    },
    {
      id: 'drywall-repair',
      name: 'Drywall Repair',
      measurementType: 'count',
      unit: 'patch',
      defaultRate: 75,
      minimumCharge: 150,
      description: 'Small to medium patches',
    },
    {
      id: 'wallpaper-removal',
      name: 'Wallpaper Removal',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 2,
      minimumCharge: 300,
      description: 'Remove and prep for paint',
    },
    {
      id: 'popcorn-removal',
      name: 'Popcorn Ceiling Removal',
      measurementType: 'area',
      unit: 'sqft',
      defaultRate: 2.5,
      minimumCharge: 500,
      description: 'Scrape, skim coat, prime',
    },
  ],

  customFields: [
    {
      key: 'project_type',
      label: 'Project Type',
      type: 'select',
      options: ['Interior Only', 'Exterior Only', 'Interior & Exterior', 'Commercial', 'Cabinet Refinishing'],
      required: true,
    },
    {
      key: 'property_type',
      label: 'Property Type',
      type: 'select',
      options: ['Single Family', 'Condo/Townhouse', 'Apartment', 'Commercial Office', 'Retail', 'Industrial'],
      required: true,
    },
    {
      key: 'total_sqft',
      label: 'Total Square Footage',
      type: 'number',
      required: true,
      helpText: 'Livable/usable square feet',
    },
    {
      key: 'num_rooms',
      label: 'Number of Rooms',
      type: 'number',
    },
    {
      key: 'ceiling_height',
      label: 'Ceiling Height',
      type: 'select',
      options: ['8ft Standard', '9ft', '10ft', 'Vaulted', 'Multi-height'],
    },
    {
      key: 'paint_grade',
      label: 'Paint Grade',
      type: 'select',
      options: ['Builder Grade', 'Standard', 'Premium', 'Ultra Premium'],
      helpText: 'Affects material cost',
    },
    {
      key: 'surface_condition',
      label: 'Surface Condition',
      type: 'select',
      options: ['Excellent', 'Good', 'Fair', 'Poor', 'Needs Major Prep'],
    },
    {
      key: 'lead_paint',
      label: 'Pre-1978 (Lead Paint Risk)',
      type: 'boolean',
      helpText: 'Requires EPA RRP certified work',
    },
    {
      key: 'occupied',
      label: 'Property Occupied',
      type: 'boolean',
      helpText: 'Affects scheduling and prep',
    },
  ],

  reports: [
    {
      id: 'revenue',
      name: 'Revenue Report',
      description: 'Total revenue by period',
      icon: 'DollarSign',
    },
    {
      id: 'profitability',
      name: 'Project Profitability',
      description: 'Profit margin per project',
      icon: 'TrendingUp',
    },
    {
      id: 'crew-productivity',
      name: 'Crew Productivity',
      description: 'Square feet painted per day',
      icon: 'Users',
    },
    {
      id: 'material-usage',
      name: 'Material Usage',
      description: 'Paint gallons, supplies tracking',
      icon: 'Package',
    },
    {
      id: 'color-history',
      name: 'Color History',
      description: 'Colors used by client/project',
      icon: 'Palette',
    },
    {
      id: 'warranty-tracker',
      name: 'Warranty Tracker',
      description: 'Active warranties by project',
      icon: 'Shield',
    },
  ],

  navigation: [
    { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Projects', href: '/jobs', icon: 'Briefcase' },
    { label: 'Bids', href: '/estimates', icon: 'FileText' },
    { label: 'Clients', href: '/contacts', icon: 'Users' },
    { label: 'Schedule', href: '/schedule', icon: 'Calendar' },
    { label: 'Painters', href: '/crew', icon: 'HardHat' },
    { label: 'Invoices', href: '/invoices', icon: 'Receipt' },
    { label: 'Expenses', href: '/expenses', icon: 'CreditCard' },
    { label: 'Reports', href: '/reports', icon: 'BarChart3' },
    { label: 'Settings', href: '/settings', icon: 'Settings' },
  ],
};

export default paintingConfig;
